#https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml
runtime: custom
env: flex
service: chat
resources:
  cpu: 1
  memory_gb: 0.6
manual_scaling:
  instances: 1