# see https://cloud.google.com/appengine/docs/standard/java11/config/appref?hl=ja
runtime: java11
instance_class: F1
entrypoint: 'java -cp "./*:./libs/*" {{mainClassName}}' #mainClassNameはgradle appengineStageで置き換えられる
